<a href="https://colab.research.google.com/github/srt3000/CE888/blob/Lab_6/Lab_4/Lab_4_my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
np.set_printoptions(precision = 3)
# np.set_printoptions(precision=3)



In [ ]:
#the value "99" corresponds to "null" = "not rated"
#Ratings are real values ranging from -10.00 to +10.00
#The first column gives the number of jokes rated by that user. The next 100 columns give the ratings for jokes 01 - 100.
column_names = list(range(0,101))
print(column_names)
data = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',names=column_names)
df= data.copy()
df



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [ ]:
df.replace(99,  np.nan, inplace=True)
df

0     1     2     3     4     5    ...   95    96    97    98    99    100
0       74.0 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      100.0  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       49.0   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       48.0   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4       91.0  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60
...      ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  100.0  0.44  7.43  9.08  2.33  3.20  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979   91.0  9.13 -8.16  8.59  9.08  0.87  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   39.0   NaN   NaN   NaN   NaN -7.77  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   37.0   NaN   NaN   NaN   NaN -9.71  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982   72.0  2.43  2.67 -3.98  4.27 -2.28  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 101 columns]

In [ ]:
#Drop the 1st column as it doesn't contain ratings, its the number of ratings that a user did
df.drop(0, axis=1, inplace=True)
df

1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 100 columns]

In [ ]:
#find the best- and the worst-rated jokes
x=[]
for i in df.columns:
  x.append(df[i].mean())
#  max_value = max(x)
print(x.index(max(x)))
print("best joke  : ",x.index(max(x))+1,"  rating : ",max(x))
print("worst joke : ",x.index(min(x))+1,"  rating : ", min(x))



49
best joke  :  50   rating :  3.6650848950824937
worst joke :  58   rating :  -3.8338796373689923


Modify and use the helper function provided in the helper_function notebook (or create your own) to label 10% of the dataset cells that are not NaNs as 99. This is your validation set. Keep the the actual values of the cells so you can use them later

In [ ]:
#Create a copy of the dataset again as df2.
df2 = df.copy()
print(df)
arr = df.values
print(arr.shape)



        1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24

In [ ]:
#rated is a 2D array with 24983 rows and 100 colums, so rated[0] is 24983 and rated[1] is 99


In [ ]:
#use the helper function provided in the helper_function notebook (or create your own) to label 10% of the dataset cells that are not NaNs as 99
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99) #all values that are not 99 are taken 
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [ ]:

new_arr, idx = replace(arr, 0.1)

In [ ]:
print(new_arr,idx)

[[-7.82  8.79 -9.66 ... 99.     nan   nan]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [  nan   nan 99.   ...   nan   nan   nan]
 ...
 [99.     nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ... 99.     nan 99.  ]] (array([ 3573, 16204,  5022, ..., 20120, 15945, 16578]), array([ 2, 15, 23, ..., 88, 62, 96]))


In [ ]:
arr[idx[0][0], idx[1][0]]


3.88

In [ ]:
new_arr[idx[0][0], idx[1][0]]


99.0

Use latent factor modeling (with 2 latent factors) to infer the hidden ratings of the users (they are labeled as "99" in the dataset) on the training set. You will have to modify at least one line in the provided sgd() function for this (and probably 2, depending on your variable names).
Iterations in sgd will take a long time to run: you can (and should) use low numbers. Try something like 10.
You can interrupt at any point the execution of this function, because the values are updated in each iteration, so if you interrupt execution you can use the latent_user_preferences and latent_item_features.

In [ ]:
data = df
n_latent_factors = 2

user_ratings = data.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [ ]:
latent_item_features


array([[0.519, 0.069],
       [0.933, 0.622],
       [0.281, 0.857],
       [0.14 , 0.752],
       [0.192, 0.891],
       [0.929, 0.041],
       [0.791, 0.331],
       [0.365, 0.95 ],
       [0.824, 0.455],
       [0.299, 0.134],
       [0.056, 0.826],
       [0.591, 0.858],
       [0.729, 0.779],
       [0.026, 0.525],
       [0.332, 0.465],
       [0.363, 0.949],
       [0.676, 0.06 ],
       [0.527, 0.091],
       [0.328, 0.23 ],
       [0.166, 0.431],
       [0.278, 0.98 ],
       [0.163, 0.882],
       [0.319, 0.239],
       [0.942, 0.783],
       [0.47 , 0.905],
       [0.048, 0.582],
       [0.763, 0.095],
       [0.134, 0.939],
       [0.462, 0.574],
       [0.729, 0.87 ],
       [0.394, 0.528],
       [0.28 , 0.986],
       [0.178, 0.506],
       [0.336, 0.295],
       [0.31 , 0.07 ],
       [0.745, 0.177],
       [0.91 , 0.014],
       [0.52 , 0.329],
       [0.661, 0.936],
       [0.665, 0.017],
       [0.551, 0.607],
       [0.82 , 0.29 ],
       [0.503, 0.241],
       [0.0

In [ ]:
latent_user_preferences


array([[0.947, 0.624],
       [0.379, 0.152],
       [0.19 , 0.355],
       ...,
       [0.12 , 0.644],
       [0.223, 0.105],
       [0.917, 0.965]])

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history


In [ ]:
num_iter = 20
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10000), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()


Iteration 0/20:	MSE=26.149958


KeyboardInterrupt: ignored

In [ ]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions


array([[-3.32 , -4.138, -4.476, ..., -1.626, -3.582, -1.606],
       [ 2.622,  2.909,  2.953, ...,  2.345,  2.509,  2.598],
       [ 4.337,  4.241,  3.958, ...,  5.571,  3.64 ,  6.419],
       ...,
       [ 0.142,  0.124,  0.105, ...,  0.229,  0.106,  0.269],
       [ 0.976,  1.   ,  0.965, ...,  1.119,  0.86 ,  1.275],
       [ 3.367,  3.493,  3.397, ...,  3.733,  3.004,  4.241]])

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

In [ ]:
comparison_data

1    ...                         100
0      (-7.82, -3.32025211288737)  ...   (nan, -1.605985336742259)
1      (4.08, 2.6219048220605345)  ...  (1.07, 2.5983754302926876)
2        (nan, 4.336754561942217)  ...    (nan, 6.418851840993601)
3       (nan, 3.5072382108842675)  ...   (nan, 3.6434066085729637)
4       (8.5, 2.8531585956459002)  ...    (1.6, 4.353864045602082)
...                           ...  ...                         ...
24978  (0.44, 2.5345575010890657)  ...  (7.43, 3.9784409189466827)
24979  (9.13, 2.4376980427861743)  ...  (8.45, 1.3986771848023385)
24980  (nan, 0.14247279657777512)  ...   (nan, 0.2687181733999538)
24981   (nan, 0.9761431296622123)  ...   (nan, 1.2752654814449162)
24982   (2.43, 3.366750555982595)  ...    (nan, 4.240668714515945)

[24983 rows x 100 columns]

Quiz


In [ ]:
#In the movies dataset, what's the rating that user 254 has given to joke 17?
x = data.loc[[254]]
x[17]

254   -1.21
Name: 17, dtype: float64

In [ ]:
movie_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Items')
users_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Users')

In [ ]:
movie_data.head()

Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [ ]:
users_data.head()

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [ ]:
#In the movies dataset, what's the loading (i.e., value) of Factor15 for the movie with ID=36657?

movie_value = movie_data.loc[movie['Movie ID']== 36657]
movie_value

Movie ID         Title   Factor1  ...  Factor13  Factor14  Factor15
97     36657  X-Men (2000)  0.811901  ...  0.642105 -1.355542   0.06779

[1 rows x 17 columns]

In [ ]:
np.argmin(movie_data['Factor10'])


47

In [ ]:
#In the movies dataset, which of the following titles corresponds to the movie with the lowest loading of factor 10?
movie_data[movie_data['Factor10'] == movie_data['Factor10'].min()]

Movie ID           Title   Factor1  ...  Factor13  Factor14  Factor15
47       597  Titanic (1997)  1.567865  ...  0.370387  2.215933  0.456127

[1 rows x 17 columns]

In [ ]:
#In the movies dataset, predict the rating that the user with ID 4469 will give to the movie with ID 4327
moviecp = movie_data.drop(['Movie ID','Title'], axis=1)
usercp = users_data.drop(['User'], axis=1)
moviecp

Factor1   Factor2   Factor3  ...  Factor13  Factor14  Factor15
0  -1.521848 -1.038507  2.027269  ...  0.403861  1.129616 -0.248806
1  -0.342185 -0.296586 -0.385962  ... -0.564415  0.506876  1.274993
2  -2.240888 -0.438815 -2.275177  ... -0.330276 -2.209004 -0.419092
3  -0.634531  2.186059 -0.066681  ... -0.819682  0.549010 -0.681191
4   0.517348 -1.456763  0.369161  ...  1.429191  0.855746 -2.292566
..       ...       ...       ...  ...       ...       ...       ...
95  0.159967 -0.051123  0.311183  ... -0.649164  0.045580  1.017861
96  1.286288  0.004957 -0.157640  ...  0.994535  0.868700 -0.487076
97  0.811901 -0.893280  0.668953  ...  0.642105 -1.355542  0.067790
98  1.161006 -0.715613  0.712633  ...  0.290714 -1.217250 -0.288130
99  1.734008  0.265436 -0.003391  ...  0.333703 -0.223382 -0.022599

[100 rows x 15 columns]

In [ ]:

items= moviecp.values
user_pref= usercp.values
rating = user_pref.dot(items.T)
ratings_df= pd.DataFrame(rating)
ratings_df

0         1         2   ...        97        98        99
0   0.389174  0.191449  0.766364  ... -0.395129 -0.522412  0.097010
1   0.883069  0.319496  0.396485  ... -0.259385 -0.455462 -0.113381
2   0.214068  0.154537  0.261073  ... -0.083633 -0.163929 -0.199840
3  -0.139366  0.129855  1.212876  ...  0.138995  0.003095 -0.524709
4  -0.038172  0.866052 -0.285316  ...  0.079577  0.070540 -0.357920
5   0.063515  0.168541  0.170626  ... -0.161995 -0.125955 -0.183417
6   0.619344  0.396214  0.205784  ... -0.376227 -0.555636  0.193396
7   0.028389  0.017066 -0.025851  ... -0.098649 -0.085649 -0.006351
8   0.033540 -0.066459  0.170744  ... -0.052109 -0.057458 -0.076232
9   0.220284  0.366293 -0.212080  ... -0.105606 -0.104062 -0.445656
10 -1.218669  0.253885  1.916883  ...  0.031380 -0.000738 -1.247069
11 -0.239497  0.321743  0.828942  ... -0.073809 -0.200035  0.009083
12 -0.505019 -0.161595  0.236184  ... -0.038103 -0.137375  0.139222
13  0.073994  0.013350 -0.123052  ...  0.225218  0.100497  0.046562
14 -0.415176  0.953211  1.720557  ... -0.225730 -0.081358 -1.333522
15  0.485341 -0.082271  0.019836  ... -0.074445 -0.057365 -0.061002
16 -0.047545  0.215901 -0.097520  ... -0.228015 -0.193371 -0.381373
17  0.181496  0.054192  0.145365  ...  0.027508  0.049276 -0.111751
18 -0.264427  0.533221  0.657465  ... -0.014485 -0.208688  0.092931
19  0.147498  0.069831  0.050346  ... -0.534355 -0.586092 -0.029751
20  0.002598  0.022087  0.234905  ... -0.172472 -0.190195 -0.062978
21 -0.571045  0.701410  0.957224  ... -0.071025 -0.133544 -0.000380
22 -0.183987 -0.146073  1.057426  ...  0.084414 -0.091907 -0.588751
23  0.564326  0.025133  0.234326  ... -0.526320 -0.461121 -0.196988
24 -0.007102  0.150055  0.428733  ... -0.166569 -0.218647 -0.155148

[25 rows x 100 columns]

In [ ]:
user = 525
movie = 664
x= users_data.loc[user].values
y = movie_data.loc[movie].drop('Title').values
print(x.dot(y))


-0.03828289238310254


In [4]:
def top_recommendation(user, no_of_rec):
  pred = {}
  for movie in movie_data.index:
    pred[movie] = predict_movie_rating(user, movie)
  pred = dict(sorted(pred.items(), key=lambda kv: kv[1], reverse=True))
  movies = list(pred.keys())
  return movies[:no_of_rec]
  
movie_data.loc[top_n_recommendation(4469, 2)]['Title']